arb-dir: lib/src/l10n
template-arb-file: app_en.arb
output-class: SuggestionsLocalizations
output-localization-file: suggestions_localizations.dart
synthetic-package: false
preferred-supported-locales: "en"
use-deferred-loading: false
